const projects = [
  {
    title: 'Digital Onboarding',
    key: 'digitalonboarding',
    url: 'https://www.digitalonboarding.com/',
    description: 'Digitally streamlining business onboarding journeys',
    tech: 'react',
  },
  {
    title: 'Datarista Inc.',
    key: 'datarista',
    url: 'http://www.datarista.com/',
    description: 'First professional ReactJS Application, Search Frame and Dashboard.',
    tech: 'react',
  },
  {
    title: 'Blockstack',
    key: 'blockstack',
    url: 'https://github.com/estermer/blockstack.org',
    description: 'Open Source Contributor to decentralize the internet using the blockchain',
    tech: 'react',
  },
  {
    title: 'Pollster',
    key: 'pollster',
    url: 'https://github.com/estermer/pollster-ui',
    description: 'An app to create and participate in polls.',
    tech: 'rails',
  },
  {
    title: 'NITPIC',
    key: 'nitpic',
    url: 'https://github.com/estermer/nitpic-ui',
    description: 'A photo sharing application.',
    tech: 'rails',
  },
  {
    title: 'Shop Mate',
    key: 'shopmate',
    url: 'https://github.com/estermer/grocery-list-app',
    description: 'Track your shopping list for your trip to the grocery store.',
    tech: 'node',
  },
  {
    title: 'Mile Logger',
    key: 'milelogger',
    url: 'https://github.com/estermer/mile-logger',
    description: 'Track and log your miles you run.',
    tech: 'node',
  },
  {
    title: 'Pokedex',
    key: 'pokedex',
    url: 'https://github.com/estermer/eric-pokedex-server',
    description: 'Keep track of pokemon using NodeJS',
    tech: 'node',
  },
  {
    title: 'Black Jack',
    key: 'blackjack',
    url: 'https://github.com/estermer/BlackJack-GA',
    description: 'A simple game of Black Jack.',
    tech: 'jquery',
  },
  {
    title: 'Liberty Notepad Generator',
    key: 'libertygen',
    url: 'https://codepen.io/estermer/pen/wWXLaz',
    description: 'A generator for standardized notes when taking student calls',
    tech: 'jquery',
  },
  {
    title: 'Pomodoro Clock',
    key: 'pomodoro',
    url: 'https://codepen.io/estermer/pen/ZOwWYj',
    description: 'A stopwatch for short sprints of work and rest.',
    tech: 'jquery',
  },
  {
    title: 'Calculator',
    key: 'calc',
    url: 'https://codepen.io/estermer/pen/LkmqkJ',
    description: 'A simple calculator',
    tech: 'jquery',
  },
  {
    title: 'Weather App',
    key: 'weatherapp',
    url: 'https://codepen.io/estermer/pen/wWvJrV',
    description: 'Using jQuery AJAX for my first API request app',
    tech: 'jquery',
  },
  {
    title: 'FreeCodeCamp',
    key: 'freecodecamp',
    url: 'https://www.freecodecamp.com/estermer',
    description: 'A free bootcamp to learn fullstack web development',
    tech: 'learning',
  },
  {
    title: 'Codepen',
    key: 'codepen',
    url: 'http://codepen.io/estermer/',
    description: 'One of my coding playgrounds',
    tech: 'learning',
  },
  {
    title: 'Khan Academy',
    key: 'khanacademy',
    url: 'https://www.khanacademy.org/profile/kaid_1090611702257418820503017/projects',
    description: 'Introduction to web development',
    tech: 'learning',
  },
  {
    title: 'Codewars',
    key: 'codewars',
    url: 'https://www.codewars.com/users/estermer',
    description: 'improving algorithm skills with friends',
    tech: 'learning',
  },
  {
    title: 'Hacker Rank',
    key: 'hackerrank',
    url: 'https://www.hackerrank.com/eric_stermer',
    description: 'improving algorithm skills',
    tech: 'learning',
  },
  {
    title: 'If Me',
    key: 'ifme',
    url: 'https://github.com/estermer/ifme',
    description:
      'Open Source Contributor to help provide a place for support for those who suffer from mental illness',
    tech: 'rails',
  },
  {
    title: 'Add-me',
    key: 'addme',
    url: 'https://github.com/JonathanGrant/AddMeForReal',
    description: 'Big Red Hack-a-thon best business idea at Cornell University, Fall 2016.',
    tech: 'node',
  },
  {
    title: 'RIPTA Reviews',
    key: 'ripta',
    url: 'https://github.com/estermer/ripta-reviews',
    description: 'HackRI 2016 submission for REV RIPTA competition.',
    tech: 'rails',
  },
];

export default projects;
